name: update_github_page
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
          token: '${{ secrets.WATCHDOG_WMS_BOT_TOKEN }}'
      - name: checkout Watchdog
        uses: actions/checkout@v2
        with:
          ref: master
          path: watchdog
          repository: klugem/watchdog  
      - name: create documentation folder
        run: |
          cd "$GITHUB_WORKSPACE"
          java -jar watchdog/jars/refBookGenerator.jar -m master/ -o refBook/
          rm -rf gh-pages/*
          mv refBook/* gh-pages/.
      - name: commit files
        run: |
          cd "$GITHUB_WORKSPACE/gh-pages"
          if [ ! -z "$(git status --porcelain)" ]; then
            curl -s -H "Authorization: token ${{ secrets.WATCHDOG_WMS_BOT_TOKEN }}" "${{ secrets.SECURE_DOWNLOAD_URL }}" | gpg --yes --no-tty --import - > /dev/null 2>&1
            git config --local user.email "kluge-watchdog@bio.ifi.lmu.de"
            git config --local user.name "watchdog-wms-bot"
            git add -A
            git commit -S --gpg-sign="${{ secrets.KEY_FINGERPRINT }}" -m "updated documentation"
            gpg --yes --no-tty --batch --delete-secret-keys "${{ secrets.KEY_FINGERPRINT }}" > /dev/null 2>&1
            git push
          fi
